/*
* generated by Xtext
*/
package at.ac.uibk.greatAdventure.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import at.ac.uibk.greatAdventure.services.GreatAdventureGrammarAccess;

public class GreatAdventureParser extends AbstractContentAssistParser {
	
	@Inject
	private GreatAdventureGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected at.ac.uibk.greatAdventure.ui.contentassist.antlr.internal.InternalGreatAdventureParser createParser() {
		at.ac.uibk.greatAdventure.ui.contentassist.antlr.internal.InternalGreatAdventureParser result = new at.ac.uibk.greatAdventure.ui.contentassist.antlr.internal.InternalGreatAdventureParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getGreetingAccess().getGroup(), "rule__Greeting__Group__0");
					put(grammarAccess.getModelAccess().getGreetingsAssignment(), "rule__Model__GreetingsAssignment");
					put(grammarAccess.getGreetingAccess().getNameAssignment_1(), "rule__Greeting__NameAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			at.ac.uibk.greatAdventure.ui.contentassist.antlr.internal.InternalGreatAdventureParser typedParser = (at.ac.uibk.greatAdventure.ui.contentassist.antlr.internal.InternalGreatAdventureParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public GreatAdventureGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GreatAdventureGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
