/*
 * generated by Xtext
 */
package at.ac.uibk.greatAdventure.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import at.ac.uibk.greatAdventure.ui.internal.GreatAdventureActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GreatAdventureExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GreatAdventureActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GreatAdventureActivator.getInstance().getInjector(GreatAdventureActivator.AT_AC_UIBK_GREATADVENTURE_GREATADVENTURE);
	}
	
}
