/*
* generated by Xtext
*/
package at.ac.uibk.greatAdventure.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class GreatAdventureGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class AdventureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Adventure");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTitleAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTitleAdventureTitleParserRuleCall_0_0 = (RuleCall)cTitleAssignment_0.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_1 = (UnorderedGroup)cGroup.eContents().get(1);
		private final Assignment cItemDefAssignment_1_0 = (Assignment)cUnorderedGroup_1.eContents().get(0);
		private final RuleCall cItemDefItemDefinitionParserRuleCall_1_0_0 = (RuleCall)cItemDefAssignment_1_0.eContents().get(0);
		private final Assignment cSceneDefAssignment_1_1 = (Assignment)cUnorderedGroup_1.eContents().get(1);
		private final RuleCall cSceneDefSceneDefinitionParserRuleCall_1_1_0 = (RuleCall)cSceneDefAssignment_1_1.eContents().get(0);
		private final Assignment cStartDefAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cStartDefStartDefinitionParserRuleCall_2_0 = (RuleCall)cStartDefAssignment_2.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_3 = (UnorderedGroup)cGroup.eContents().get(3);
		private final Assignment cItemDefAssignment_3_0 = (Assignment)cUnorderedGroup_3.eContents().get(0);
		private final RuleCall cItemDefItemDefinitionParserRuleCall_3_0_0 = (RuleCall)cItemDefAssignment_3_0.eContents().get(0);
		private final Assignment cSceneDefAssignment_3_1 = (Assignment)cUnorderedGroup_3.eContents().get(1);
		private final RuleCall cSceneDefSceneDefinitionParserRuleCall_3_1_0 = (RuleCall)cSceneDefAssignment_3_1.eContents().get(0);
		
		//Adventure:
		//	title=AdventureTitle (itemDef+=ItemDefinition+ & sceneDef+=SceneDefinition+)* startDef=StartDefinition
		//	(itemDef+=ItemDefinition+ & sceneDef+=SceneDefinition+)*;
		public ParserRule getRule() { return rule; }

		//title=AdventureTitle (itemDef+=ItemDefinition+ & sceneDef+=SceneDefinition+)* startDef=StartDefinition
		//(itemDef+=ItemDefinition+ & sceneDef+=SceneDefinition+)*
		public Group getGroup() { return cGroup; }

		//title=AdventureTitle
		public Assignment getTitleAssignment_0() { return cTitleAssignment_0; }

		//AdventureTitle
		public RuleCall getTitleAdventureTitleParserRuleCall_0_0() { return cTitleAdventureTitleParserRuleCall_0_0; }

		//(itemDef+=ItemDefinition+ & sceneDef+=SceneDefinition+)*
		public UnorderedGroup getUnorderedGroup_1() { return cUnorderedGroup_1; }

		//itemDef+=ItemDefinition+
		public Assignment getItemDefAssignment_1_0() { return cItemDefAssignment_1_0; }

		//ItemDefinition
		public RuleCall getItemDefItemDefinitionParserRuleCall_1_0_0() { return cItemDefItemDefinitionParserRuleCall_1_0_0; }

		//sceneDef+=SceneDefinition+
		public Assignment getSceneDefAssignment_1_1() { return cSceneDefAssignment_1_1; }

		//SceneDefinition
		public RuleCall getSceneDefSceneDefinitionParserRuleCall_1_1_0() { return cSceneDefSceneDefinitionParserRuleCall_1_1_0; }

		//startDef=StartDefinition
		public Assignment getStartDefAssignment_2() { return cStartDefAssignment_2; }

		//StartDefinition
		public RuleCall getStartDefStartDefinitionParserRuleCall_2_0() { return cStartDefStartDefinitionParserRuleCall_2_0; }

		//(itemDef+=ItemDefinition+ & sceneDef+=SceneDefinition+)*
		public UnorderedGroup getUnorderedGroup_3() { return cUnorderedGroup_3; }

		//itemDef+=ItemDefinition+
		public Assignment getItemDefAssignment_3_0() { return cItemDefAssignment_3_0; }

		//ItemDefinition
		public RuleCall getItemDefItemDefinitionParserRuleCall_3_0_0() { return cItemDefItemDefinitionParserRuleCall_3_0_0; }

		//sceneDef+=SceneDefinition+
		public Assignment getSceneDefAssignment_3_1() { return cSceneDefAssignment_3_1; }

		//SceneDefinition
		public RuleCall getSceneDefSceneDefinitionParserRuleCall_3_1_0() { return cSceneDefSceneDefinitionParserRuleCall_3_1_0; }
	}

	public class AdventureTitleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AdventureTitle");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//AdventureTitle:
		//	name=STRING;
		public ParserRule getRule() { return rule; }

		//name=STRING
		public Assignment getNameAssignment() { return cNameAssignment; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_0() { return cNameSTRINGTerminalRuleCall_0; }
	}

	public class ItemDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ItemDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Keyword cAKeyword_0_0 = (Keyword)cAlternatives_0.eContents().get(0);
		private final Keyword cAnKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final UnorderedGroup cUnorderedGroup_3 = (UnorderedGroup)cGroup.eContents().get(3);
		private final Assignment cPickupAssignment_3_0 = (Assignment)cUnorderedGroup_3.eContents().get(0);
		private final Keyword cPickupCanBePickedUpKeyword_3_0_0 = (Keyword)cPickupAssignment_3_0.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cUnorderedGroup_3.eContents().get(1);
		private final Keyword cLooksLikeKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Assignment cImgAssignment_3_1_1 = (Assignment)cGroup_3_1.eContents().get(1);
		private final RuleCall cImgSTRINGTerminalRuleCall_3_1_1_0 = (RuleCall)cImgAssignment_3_1_1.eContents().get(0);
		private final Assignment cUsesAssignment_3_2 = (Assignment)cUnorderedGroup_3.eContents().get(2);
		private final RuleCall cUsesUseDefinitionParserRuleCall_3_2_0 = (RuleCall)cUsesAssignment_3_2.eContents().get(0);
		
		//ItemDefinition:
		//	("A" | "An") name=STRING ":" (pickup?="- can be picked up"? & "- looks like" img=STRING & uses+=UseDefinition*);
		public ParserRule getRule() { return rule; }

		//("A" | "An") name=STRING ":" (pickup?="- can be picked up"? & "- looks like" img=STRING & uses+=UseDefinition*)
		public Group getGroup() { return cGroup; }

		//"A" | "An"
		public Alternatives getAlternatives_0() { return cAlternatives_0; }

		//"A"
		public Keyword getAKeyword_0_0() { return cAKeyword_0_0; }

		//"An"
		public Keyword getAnKeyword_0_1() { return cAnKeyword_0_1; }

		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }

		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }

		//pickup?="- can be picked up"? & "- looks like" img=STRING & uses+=UseDefinition*
		public UnorderedGroup getUnorderedGroup_3() { return cUnorderedGroup_3; }

		//pickup?="- can be picked up"?
		public Assignment getPickupAssignment_3_0() { return cPickupAssignment_3_0; }

		//"- can be picked up"
		public Keyword getPickupCanBePickedUpKeyword_3_0_0() { return cPickupCanBePickedUpKeyword_3_0_0; }

		//"- looks like" img=STRING
		public Group getGroup_3_1() { return cGroup_3_1; }

		//"- looks like"
		public Keyword getLooksLikeKeyword_3_1_0() { return cLooksLikeKeyword_3_1_0; }

		//img=STRING
		public Assignment getImgAssignment_3_1_1() { return cImgAssignment_3_1_1; }

		//STRING
		public RuleCall getImgSTRINGTerminalRuleCall_3_1_1_0() { return cImgSTRINGTerminalRuleCall_3_1_1_0; }

		//uses+=UseDefinition*
		public Assignment getUsesAssignment_3_2() { return cUsesAssignment_3_2; }

		//UseDefinition
		public RuleCall getUsesUseDefinitionParserRuleCall_3_2_0() { return cUsesUseDefinitionParserRuleCall_3_2_0; }
	}

	public class UseDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "UseDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cYouCanKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cWithKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cItWhichKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final UnorderedGroup cUnorderedGroup_4 = (UnorderedGroup)cGroup.eContents().get(4);
		private final Group cGroup_4_0 = (Group)cUnorderedGroup_4.eContents().get(0);
		private final Keyword cRequiresKeyword_4_0_0 = (Keyword)cGroup_4_0.eContents().get(0);
		private final Assignment cReqsAssignment_4_0_1 = (Assignment)cGroup_4_0.eContents().get(1);
		private final CrossReference cReqsItemDefinitionCrossReference_4_0_1_0 = (CrossReference)cReqsAssignment_4_0_1.eContents().get(0);
		private final RuleCall cReqsItemDefinitionIDTerminalRuleCall_4_0_1_0_1 = (RuleCall)cReqsItemDefinitionCrossReference_4_0_1_0.eContents().get(1);
		private final Group cGroup_4_0_2 = (Group)cGroup_4_0.eContents().get(2);
		private final Keyword cOrSaysKeyword_4_0_2_0 = (Keyword)cGroup_4_0_2.eContents().get(0);
		private final Assignment cAltTextAssignment_4_0_2_1 = (Assignment)cGroup_4_0_2.eContents().get(1);
		private final RuleCall cAltTextSTRINGTerminalRuleCall_4_0_2_1_0 = (RuleCall)cAltTextAssignment_4_0_2_1.eContents().get(0);
		private final Group cGroup_4_1 = (Group)cUnorderedGroup_4.eContents().get(1);
		private final Keyword cAddsKeyword_4_1_0 = (Keyword)cGroup_4_1.eContents().get(0);
		private final Assignment cAddsAssignment_4_1_1 = (Assignment)cGroup_4_1.eContents().get(1);
		private final CrossReference cAddsItemDefinitionCrossReference_4_1_1_0 = (CrossReference)cAddsAssignment_4_1_1.eContents().get(0);
		private final RuleCall cAddsItemDefinitionIDTerminalRuleCall_4_1_1_0_1 = (RuleCall)cAddsItemDefinitionCrossReference_4_1_1_0.eContents().get(1);
		private final Group cGroup_4_1_2 = (Group)cGroup_4_1.eContents().get(2);
		private final Keyword cCommaKeyword_4_1_2_0 = (Keyword)cGroup_4_1_2.eContents().get(0);
		private final Assignment cAddsAssignment_4_1_2_1 = (Assignment)cGroup_4_1_2.eContents().get(1);
		private final CrossReference cAddsItemDefinitionCrossReference_4_1_2_1_0 = (CrossReference)cAddsAssignment_4_1_2_1.eContents().get(0);
		private final RuleCall cAddsItemDefinitionIDTerminalRuleCall_4_1_2_1_0_1 = (RuleCall)cAddsItemDefinitionCrossReference_4_1_2_1_0.eContents().get(1);
		private final Group cGroup_4_2 = (Group)cUnorderedGroup_4.eContents().get(2);
		private final Keyword cRemovesKeyword_4_2_0 = (Keyword)cGroup_4_2.eContents().get(0);
		private final Assignment cDelsAssignment_4_2_1 = (Assignment)cGroup_4_2.eContents().get(1);
		private final CrossReference cDelsItemDefinitionCrossReference_4_2_1_0 = (CrossReference)cDelsAssignment_4_2_1.eContents().get(0);
		private final RuleCall cDelsItemDefinitionIDTerminalRuleCall_4_2_1_0_1 = (RuleCall)cDelsItemDefinitionCrossReference_4_2_1_0.eContents().get(1);
		private final Group cGroup_4_2_2 = (Group)cGroup_4_2.eContents().get(2);
		private final Keyword cCommaKeyword_4_2_2_0 = (Keyword)cGroup_4_2_2.eContents().get(0);
		private final Assignment cDelsAssignment_4_2_2_1 = (Assignment)cGroup_4_2_2.eContents().get(1);
		private final CrossReference cDelsItemDefinitionCrossReference_4_2_2_1_0 = (CrossReference)cDelsAssignment_4_2_2_1.eContents().get(0);
		private final RuleCall cDelsItemDefinitionIDTerminalRuleCall_4_2_2_1_0_1 = (RuleCall)cDelsItemDefinitionCrossReference_4_2_2_1_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cUnorderedGroup_4.eContents().get(3);
		private final Keyword cSaysKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cTextAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cTextSTRINGTerminalRuleCall_4_3_1_0 = (RuleCall)cTextAssignment_4_3_1.eContents().get(0);
		private final Group cGroup_4_4 = (Group)cUnorderedGroup_4.eContents().get(4);
		private final Keyword cTakesYouToTheKeyword_4_4_0 = (Keyword)cGroup_4_4.eContents().get(0);
		private final Assignment cFollowSceneAssignment_4_4_1 = (Assignment)cGroup_4_4.eContents().get(1);
		private final CrossReference cFollowSceneSceneDefinitionCrossReference_4_4_1_0 = (CrossReference)cFollowSceneAssignment_4_4_1.eContents().get(0);
		private final RuleCall cFollowSceneSceneDefinitionIDTerminalRuleCall_4_4_1_0_1 = (RuleCall)cFollowSceneSceneDefinitionCrossReference_4_4_1_0.eContents().get(1);
		
		//UseDefinition:
		//	"- you can" name+=STRING "with"? "it, which:" (("+ requires" reqs+=[ItemDefinition] ("or says" altText+=STRING)?)? &
		//	("+ adds" adds+=[ItemDefinition] ("," adds+=[ItemDefinition])*)? & ("+ removes" dels+=[ItemDefinition] (","
		//	dels+=[ItemDefinition])*)? & ("+ says" text+=STRING)? & ("+ takes you to the" followScene=[SceneDefinition])?);
		public ParserRule getRule() { return rule; }

		//"- you can" name+=STRING "with"? "it, which:" (("+ requires" reqs+=[ItemDefinition] ("or says" altText+=STRING)?)? &
		//("+ adds" adds+=[ItemDefinition] ("," adds+=[ItemDefinition])*)? & ("+ removes" dels+=[ItemDefinition] (","
		//dels+=[ItemDefinition])*)? & ("+ says" text+=STRING)? & ("+ takes you to the" followScene=[SceneDefinition])?)
		public Group getGroup() { return cGroup; }

		//"- you can"
		public Keyword getYouCanKeyword_0() { return cYouCanKeyword_0; }

		//name+=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }

		//"with"?
		public Keyword getWithKeyword_2() { return cWithKeyword_2; }

		//"it, which:"
		public Keyword getItWhichKeyword_3() { return cItWhichKeyword_3; }

		//("+ requires" reqs+=[ItemDefinition] ("or says" altText+=STRING)?)? & ("+ adds" adds+=[ItemDefinition] (","
		//adds+=[ItemDefinition])*)? & ("+ removes" dels+=[ItemDefinition] ("," dels+=[ItemDefinition])*)? & ("+ says"
		//text+=STRING)? & ("+ takes you to the" followScene=[SceneDefinition])?
		public UnorderedGroup getUnorderedGroup_4() { return cUnorderedGroup_4; }

		//("+ requires" reqs+=[ItemDefinition] ("or says" altText+=STRING)?)?
		public Group getGroup_4_0() { return cGroup_4_0; }

		//"+ requires"
		public Keyword getRequiresKeyword_4_0_0() { return cRequiresKeyword_4_0_0; }

		//reqs+=[ItemDefinition]
		public Assignment getReqsAssignment_4_0_1() { return cReqsAssignment_4_0_1; }

		//[ItemDefinition]
		public CrossReference getReqsItemDefinitionCrossReference_4_0_1_0() { return cReqsItemDefinitionCrossReference_4_0_1_0; }

		//ID
		public RuleCall getReqsItemDefinitionIDTerminalRuleCall_4_0_1_0_1() { return cReqsItemDefinitionIDTerminalRuleCall_4_0_1_0_1; }

		//("or says" altText+=STRING)?
		public Group getGroup_4_0_2() { return cGroup_4_0_2; }

		//"or says"
		public Keyword getOrSaysKeyword_4_0_2_0() { return cOrSaysKeyword_4_0_2_0; }

		//altText+=STRING
		public Assignment getAltTextAssignment_4_0_2_1() { return cAltTextAssignment_4_0_2_1; }

		//STRING
		public RuleCall getAltTextSTRINGTerminalRuleCall_4_0_2_1_0() { return cAltTextSTRINGTerminalRuleCall_4_0_2_1_0; }

		//("+ adds" adds+=[ItemDefinition] ("," adds+=[ItemDefinition])*)?
		public Group getGroup_4_1() { return cGroup_4_1; }

		//"+ adds"
		public Keyword getAddsKeyword_4_1_0() { return cAddsKeyword_4_1_0; }

		//adds+=[ItemDefinition]
		public Assignment getAddsAssignment_4_1_1() { return cAddsAssignment_4_1_1; }

		//[ItemDefinition]
		public CrossReference getAddsItemDefinitionCrossReference_4_1_1_0() { return cAddsItemDefinitionCrossReference_4_1_1_0; }

		//ID
		public RuleCall getAddsItemDefinitionIDTerminalRuleCall_4_1_1_0_1() { return cAddsItemDefinitionIDTerminalRuleCall_4_1_1_0_1; }

		//("," adds+=[ItemDefinition])*
		public Group getGroup_4_1_2() { return cGroup_4_1_2; }

		//","
		public Keyword getCommaKeyword_4_1_2_0() { return cCommaKeyword_4_1_2_0; }

		//adds+=[ItemDefinition]
		public Assignment getAddsAssignment_4_1_2_1() { return cAddsAssignment_4_1_2_1; }

		//[ItemDefinition]
		public CrossReference getAddsItemDefinitionCrossReference_4_1_2_1_0() { return cAddsItemDefinitionCrossReference_4_1_2_1_0; }

		//ID
		public RuleCall getAddsItemDefinitionIDTerminalRuleCall_4_1_2_1_0_1() { return cAddsItemDefinitionIDTerminalRuleCall_4_1_2_1_0_1; }

		//("+ removes" dels+=[ItemDefinition] ("," dels+=[ItemDefinition])*)?
		public Group getGroup_4_2() { return cGroup_4_2; }

		//"+ removes"
		public Keyword getRemovesKeyword_4_2_0() { return cRemovesKeyword_4_2_0; }

		//dels+=[ItemDefinition]
		public Assignment getDelsAssignment_4_2_1() { return cDelsAssignment_4_2_1; }

		//[ItemDefinition]
		public CrossReference getDelsItemDefinitionCrossReference_4_2_1_0() { return cDelsItemDefinitionCrossReference_4_2_1_0; }

		//ID
		public RuleCall getDelsItemDefinitionIDTerminalRuleCall_4_2_1_0_1() { return cDelsItemDefinitionIDTerminalRuleCall_4_2_1_0_1; }

		//("," dels+=[ItemDefinition])*
		public Group getGroup_4_2_2() { return cGroup_4_2_2; }

		//","
		public Keyword getCommaKeyword_4_2_2_0() { return cCommaKeyword_4_2_2_0; }

		//dels+=[ItemDefinition]
		public Assignment getDelsAssignment_4_2_2_1() { return cDelsAssignment_4_2_2_1; }

		//[ItemDefinition]
		public CrossReference getDelsItemDefinitionCrossReference_4_2_2_1_0() { return cDelsItemDefinitionCrossReference_4_2_2_1_0; }

		//ID
		public RuleCall getDelsItemDefinitionIDTerminalRuleCall_4_2_2_1_0_1() { return cDelsItemDefinitionIDTerminalRuleCall_4_2_2_1_0_1; }

		//("+ says" text+=STRING)?
		public Group getGroup_4_3() { return cGroup_4_3; }

		//"+ says"
		public Keyword getSaysKeyword_4_3_0() { return cSaysKeyword_4_3_0; }

		//text+=STRING
		public Assignment getTextAssignment_4_3_1() { return cTextAssignment_4_3_1; }

		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_4_3_1_0() { return cTextSTRINGTerminalRuleCall_4_3_1_0; }

		//("+ takes you to the" followScene=[SceneDefinition])?
		public Group getGroup_4_4() { return cGroup_4_4; }

		//"+ takes you to the"
		public Keyword getTakesYouToTheKeyword_4_4_0() { return cTakesYouToTheKeyword_4_4_0; }

		//followScene=[SceneDefinition]
		public Assignment getFollowSceneAssignment_4_4_1() { return cFollowSceneAssignment_4_4_1; }

		//[SceneDefinition]
		public CrossReference getFollowSceneSceneDefinitionCrossReference_4_4_1_0() { return cFollowSceneSceneDefinitionCrossReference_4_4_1_0; }

		//ID
		public RuleCall getFollowSceneSceneDefinitionIDTerminalRuleCall_4_4_1_0_1() { return cFollowSceneSceneDefinitionIDTerminalRuleCall_4_4_1_0_1; }
	}

	public class SceneDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SceneDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTheKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLooksLikeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cImgAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cImgSTRINGTerminalRuleCall_3_0 = (RuleCall)cImgAssignment_3.eContents().get(0);
		private final Alternatives cAlternatives_4 = (Alternatives)cGroup.eContents().get(4);
		private final Group cGroup_4_0 = (Group)cAlternatives_4.eContents().get(0);
		private final Keyword cAndInItAreKeyword_4_0_0 = (Keyword)cGroup_4_0.eContents().get(0);
		private final Assignment cItemsAssignment_4_0_1 = (Assignment)cGroup_4_0.eContents().get(1);
		private final RuleCall cItemsItemPositionDefinitionParserRuleCall_4_0_1_0 = (RuleCall)cItemsAssignment_4_0_1.eContents().get(0);
		private final Keyword cFullStopKeyword_4_1 = (Keyword)cAlternatives_4.eContents().get(1);
		
		//SceneDefinition:
		//	"The" name=STRING "looks like" img=STRING ("and in it are:" items+=ItemPositionDefinition+ | ".");
		public ParserRule getRule() { return rule; }

		//"The" name=STRING "looks like" img=STRING ("and in it are:" items+=ItemPositionDefinition+ | ".")
		public Group getGroup() { return cGroup; }

		//"The"
		public Keyword getTheKeyword_0() { return cTheKeyword_0; }

		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }

		//"looks like"
		public Keyword getLooksLikeKeyword_2() { return cLooksLikeKeyword_2; }

		//img=STRING
		public Assignment getImgAssignment_3() { return cImgAssignment_3; }

		//STRING
		public RuleCall getImgSTRINGTerminalRuleCall_3_0() { return cImgSTRINGTerminalRuleCall_3_0; }

		//"and in it are:" items+=ItemPositionDefinition+ | "."
		public Alternatives getAlternatives_4() { return cAlternatives_4; }

		//"and in it are:" items+=ItemPositionDefinition+
		public Group getGroup_4_0() { return cGroup_4_0; }

		//"and in it are:"
		public Keyword getAndInItAreKeyword_4_0_0() { return cAndInItAreKeyword_4_0_0; }

		//items+=ItemPositionDefinition+
		public Assignment getItemsAssignment_4_0_1() { return cItemsAssignment_4_0_1; }

		//ItemPositionDefinition
		public RuleCall getItemsItemPositionDefinitionParserRuleCall_4_0_1_0() { return cItemsItemPositionDefinitionParserRuleCall_4_0_1_0; }

		//"."
		public Keyword getFullStopKeyword_4_1() { return cFullStopKeyword_4_1; }
	}

	public class ItemPositionDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ItemPositionDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cItemAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cItemItemDefinitionCrossReference_1_0 = (CrossReference)cItemAssignment_1.eContents().get(0);
		private final RuleCall cItemItemDefinitionIDTerminalRuleCall_1_0_1 = (RuleCall)cItemItemDefinitionCrossReference_1_0.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cAtKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cXposAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cXposINTTerminalRuleCall_2_2_0 = (RuleCall)cXposAssignment_2_2.eContents().get(0);
		private final Keyword cCommaKeyword_2_3 = (Keyword)cGroup_2.eContents().get(3);
		private final Assignment cYposAssignment_2_4 = (Assignment)cGroup_2.eContents().get(4);
		private final RuleCall cYposINTTerminalRuleCall_2_4_0 = (RuleCall)cYposAssignment_2_4.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2_5 = (Keyword)cGroup_2.eContents().get(5);
		
		//ItemPositionDefinition:
		//	"- a" item=[ItemDefinition] ("at" "(" xpos=INT "," ypos=INT ")")?;
		public ParserRule getRule() { return rule; }

		//"- a" item=[ItemDefinition] ("at" "(" xpos=INT "," ypos=INT ")")?
		public Group getGroup() { return cGroup; }

		//"- a"
		public Keyword getAKeyword_0() { return cAKeyword_0; }

		//item=[ItemDefinition]
		public Assignment getItemAssignment_1() { return cItemAssignment_1; }

		//[ItemDefinition]
		public CrossReference getItemItemDefinitionCrossReference_1_0() { return cItemItemDefinitionCrossReference_1_0; }

		//ID
		public RuleCall getItemItemDefinitionIDTerminalRuleCall_1_0_1() { return cItemItemDefinitionIDTerminalRuleCall_1_0_1; }

		//("at" "(" xpos=INT "," ypos=INT ")")?
		public Group getGroup_2() { return cGroup_2; }

		//"at"
		public Keyword getAtKeyword_2_0() { return cAtKeyword_2_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_2_1() { return cLeftParenthesisKeyword_2_1; }

		//xpos=INT
		public Assignment getXposAssignment_2_2() { return cXposAssignment_2_2; }

		//INT
		public RuleCall getXposINTTerminalRuleCall_2_2_0() { return cXposINTTerminalRuleCall_2_2_0; }

		//","
		public Keyword getCommaKeyword_2_3() { return cCommaKeyword_2_3; }

		//ypos=INT
		public Assignment getYposAssignment_2_4() { return cYposAssignment_2_4; }

		//INT
		public RuleCall getYposINTTerminalRuleCall_2_4_0() { return cYposINTTerminalRuleCall_2_4_0; }

		//")"
		public Keyword getRightParenthesisKeyword_2_5() { return cRightParenthesisKeyword_2_5; }
	}

	public class StartDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "StartDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInTheBeginningYouKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_1 = (UnorderedGroup)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cUnorderedGroup_1.eContents().get(0);
		private final Keyword cAreAtTheKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Assignment cStartLocAssignment_1_0_1 = (Assignment)cGroup_1_0.eContents().get(1);
		private final CrossReference cStartLocSceneDefinitionCrossReference_1_0_1_0 = (CrossReference)cStartLocAssignment_1_0_1.eContents().get(0);
		private final RuleCall cStartLocSceneDefinitionIDTerminalRuleCall_1_0_1_0_1 = (RuleCall)cStartLocSceneDefinitionCrossReference_1_0_1_0.eContents().get(1);
		private final Group cGroup_1_1 = (Group)cUnorderedGroup_1.eContents().get(1);
		private final Keyword cHaveKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Assignment cStartItemsAssignment_1_1_1 = (Assignment)cGroup_1_1.eContents().get(1);
		private final CrossReference cStartItemsItemDefinitionCrossReference_1_1_1_0 = (CrossReference)cStartItemsAssignment_1_1_1.eContents().get(0);
		private final RuleCall cStartItemsItemDefinitionIDTerminalRuleCall_1_1_1_0_1 = (RuleCall)cStartItemsItemDefinitionCrossReference_1_1_1_0.eContents().get(1);
		private final Group cGroup_1_1_2 = (Group)cGroup_1_1.eContents().get(2);
		private final Keyword cCommaKeyword_1_1_2_0 = (Keyword)cGroup_1_1_2.eContents().get(0);
		private final Assignment cStartItemsAssignment_1_1_2_1 = (Assignment)cGroup_1_1_2.eContents().get(1);
		private final CrossReference cStartItemsItemDefinitionCrossReference_1_1_2_1_0 = (CrossReference)cStartItemsAssignment_1_1_2_1.eContents().get(0);
		private final RuleCall cStartItemsItemDefinitionIDTerminalRuleCall_1_1_2_1_0_1 = (RuleCall)cStartItemsItemDefinitionCrossReference_1_1_2_1_0.eContents().get(1);
		
		//StartDefinition:
		//	"In the beginning you:" ("- are at the" startLoc=[SceneDefinition] & ("- have" startItems+=[ItemDefinition] (","
		//	startItems+=[ItemDefinition])*)?);
		public ParserRule getRule() { return rule; }

		//"In the beginning you:" ("- are at the" startLoc=[SceneDefinition] & ("- have" startItems+=[ItemDefinition] (","
		//startItems+=[ItemDefinition])*)?)
		public Group getGroup() { return cGroup; }

		//"In the beginning you:"
		public Keyword getInTheBeginningYouKeyword_0() { return cInTheBeginningYouKeyword_0; }

		//"- are at the" startLoc=[SceneDefinition] & ("- have" startItems+=[ItemDefinition] ("," startItems+=[ItemDefinition])*)?
		public UnorderedGroup getUnorderedGroup_1() { return cUnorderedGroup_1; }

		//"- are at the" startLoc=[SceneDefinition]
		public Group getGroup_1_0() { return cGroup_1_0; }

		//"- are at the"
		public Keyword getAreAtTheKeyword_1_0_0() { return cAreAtTheKeyword_1_0_0; }

		//startLoc=[SceneDefinition]
		public Assignment getStartLocAssignment_1_0_1() { return cStartLocAssignment_1_0_1; }

		//[SceneDefinition]
		public CrossReference getStartLocSceneDefinitionCrossReference_1_0_1_0() { return cStartLocSceneDefinitionCrossReference_1_0_1_0; }

		//ID
		public RuleCall getStartLocSceneDefinitionIDTerminalRuleCall_1_0_1_0_1() { return cStartLocSceneDefinitionIDTerminalRuleCall_1_0_1_0_1; }

		//("- have" startItems+=[ItemDefinition] ("," startItems+=[ItemDefinition])*)?
		public Group getGroup_1_1() { return cGroup_1_1; }

		//"- have"
		public Keyword getHaveKeyword_1_1_0() { return cHaveKeyword_1_1_0; }

		//startItems+=[ItemDefinition]
		public Assignment getStartItemsAssignment_1_1_1() { return cStartItemsAssignment_1_1_1; }

		//[ItemDefinition]
		public CrossReference getStartItemsItemDefinitionCrossReference_1_1_1_0() { return cStartItemsItemDefinitionCrossReference_1_1_1_0; }

		//ID
		public RuleCall getStartItemsItemDefinitionIDTerminalRuleCall_1_1_1_0_1() { return cStartItemsItemDefinitionIDTerminalRuleCall_1_1_1_0_1; }

		//("," startItems+=[ItemDefinition])*
		public Group getGroup_1_1_2() { return cGroup_1_1_2; }

		//","
		public Keyword getCommaKeyword_1_1_2_0() { return cCommaKeyword_1_1_2_0; }

		//startItems+=[ItemDefinition]
		public Assignment getStartItemsAssignment_1_1_2_1() { return cStartItemsAssignment_1_1_2_1; }

		//[ItemDefinition]
		public CrossReference getStartItemsItemDefinitionCrossReference_1_1_2_1_0() { return cStartItemsItemDefinitionCrossReference_1_1_2_1_0; }

		//ID
		public RuleCall getStartItemsItemDefinitionIDTerminalRuleCall_1_1_2_1_0_1() { return cStartItemsItemDefinitionIDTerminalRuleCall_1_1_2_1_0_1; }
	}
	
	
	private AdventureElements pAdventure;
	private AdventureTitleElements pAdventureTitle;
	private ItemDefinitionElements pItemDefinition;
	private UseDefinitionElements pUseDefinition;
	private SceneDefinitionElements pSceneDefinition;
	private ItemPositionDefinitionElements pItemPositionDefinition;
	private StartDefinitionElements pStartDefinition;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public GreatAdventureGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("at.ac.uibk.greatAdventure.GreatAdventure".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Adventure:
	//	title=AdventureTitle (itemDef+=ItemDefinition+ & sceneDef+=SceneDefinition+)* startDef=StartDefinition
	//	(itemDef+=ItemDefinition+ & sceneDef+=SceneDefinition+)*;
	public AdventureElements getAdventureAccess() {
		return (pAdventure != null) ? pAdventure : (pAdventure = new AdventureElements());
	}
	
	public ParserRule getAdventureRule() {
		return getAdventureAccess().getRule();
	}

	//AdventureTitle:
	//	name=STRING;
	public AdventureTitleElements getAdventureTitleAccess() {
		return (pAdventureTitle != null) ? pAdventureTitle : (pAdventureTitle = new AdventureTitleElements());
	}
	
	public ParserRule getAdventureTitleRule() {
		return getAdventureTitleAccess().getRule();
	}

	//ItemDefinition:
	//	("A" | "An") name=STRING ":" (pickup?="- can be picked up"? & "- looks like" img=STRING & uses+=UseDefinition*);
	public ItemDefinitionElements getItemDefinitionAccess() {
		return (pItemDefinition != null) ? pItemDefinition : (pItemDefinition = new ItemDefinitionElements());
	}
	
	public ParserRule getItemDefinitionRule() {
		return getItemDefinitionAccess().getRule();
	}

	//UseDefinition:
	//	"- you can" name+=STRING "with"? "it, which:" (("+ requires" reqs+=[ItemDefinition] ("or says" altText+=STRING)?)? &
	//	("+ adds" adds+=[ItemDefinition] ("," adds+=[ItemDefinition])*)? & ("+ removes" dels+=[ItemDefinition] (","
	//	dels+=[ItemDefinition])*)? & ("+ says" text+=STRING)? & ("+ takes you to the" followScene=[SceneDefinition])?);
	public UseDefinitionElements getUseDefinitionAccess() {
		return (pUseDefinition != null) ? pUseDefinition : (pUseDefinition = new UseDefinitionElements());
	}
	
	public ParserRule getUseDefinitionRule() {
		return getUseDefinitionAccess().getRule();
	}

	//SceneDefinition:
	//	"The" name=STRING "looks like" img=STRING ("and in it are:" items+=ItemPositionDefinition+ | ".");
	public SceneDefinitionElements getSceneDefinitionAccess() {
		return (pSceneDefinition != null) ? pSceneDefinition : (pSceneDefinition = new SceneDefinitionElements());
	}
	
	public ParserRule getSceneDefinitionRule() {
		return getSceneDefinitionAccess().getRule();
	}

	//ItemPositionDefinition:
	//	"- a" item=[ItemDefinition] ("at" "(" xpos=INT "," ypos=INT ")")?;
	public ItemPositionDefinitionElements getItemPositionDefinitionAccess() {
		return (pItemPositionDefinition != null) ? pItemPositionDefinition : (pItemPositionDefinition = new ItemPositionDefinitionElements());
	}
	
	public ParserRule getItemPositionDefinitionRule() {
		return getItemPositionDefinitionAccess().getRule();
	}

	//StartDefinition:
	//	"In the beginning you:" ("- are at the" startLoc=[SceneDefinition] & ("- have" startItems+=[ItemDefinition] (","
	//	startItems+=[ItemDefinition])*)?);
	public StartDefinitionElements getStartDefinitionAccess() {
		return (pStartDefinition != null) ? pStartDefinition : (pStartDefinition = new StartDefinitionElements());
	}
	
	public ParserRule getStartDefinitionRule() {
		return getStartDefinitionAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
