/*
* generated by Xtext
*/
package at.ac.uibk.greatAdventure.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GreatAdventureAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("at/ac/uibk/greatAdventure/parser/antlr/internal/InternalGreatAdventure.tokens");
	}
}
