/*
* generated by Xtext
*/
package at.ac.uibk.greatAdventure;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class GreatAdventureUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return at.ac.uibk.greatAdventure.ui.internal.GreatAdventureActivator.getInstance().getInjector("at.ac.uibk.greatAdventure.GreatAdventure");
	}
	
}
