/*
 * generated by Xtext
 */
package at.ac.uibk.greatAdventure.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractGreatAdventureValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(at.ac.uibk.greatAdventure.greatAdventure.GreatAdventurePackage.eINSTANCE);
		return result;
	}
}
