/**
 * generated by Xtext
 */
package at.ac.uibk.greatAdventure.validation;

import at.ac.uibk.greatAdventure.validation.AbstractGreatAdventureValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class GreatAdventureValidator extends AbstractGreatAdventureValidator {
}
