/*
 * generated by Xtext
 */
package at.ac.uibk.greatAdventure;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GreatAdventureRuntimeModule extends at.ac.uibk.greatAdventure.AbstractGreatAdventureRuntimeModule {

}
