/*
* generated by Xtext
*/
package at.ac.uibk.greatAdventure;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class GreatAdventureStandaloneSetup extends GreatAdventureStandaloneSetupGenerated{

	public static void doSetup() {
		new GreatAdventureStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

