/**
 * generated by Xtext
 */
package at.ac.uibk.greatAdventure.ui.contentassist;

import at.ac.uibk.greatAdventure.ui.contentassist.AbstractGreatAdventureProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class GreatAdventureProposalProvider extends AbstractGreatAdventureProposalProvider {
}
