/*
 * generated by Xtext
 */
package at.ac.uibk.greatAdventure.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GreatAdventureUiModule extends at.ac.uibk.greatAdventure.ui.AbstractGreatAdventureUiModule {
	public GreatAdventureUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
